### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by mrmeeseeks2014** [SnaffCon/Snaffler#118]
I am trying to download and compile Snaffler into and exe.
I downloaded Snaffler master folder from: https://github.com/SnaffCon/Snaffler

I downloaded .NET developer framework from: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

I opened cmd and navigated to the snaffler-master\snaffler folder, then ran c:\Windows\[Microsoft.NET](https://microsoft.net/)\Framework\v4.0.30319\csc.exe /t:exe /out:snaffler.exe Snaffler.cs

Received the following results:

Microsoft (R) Visual C# Compiler version 4.8.4084.0

for C# 5

Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

Snaffler.cs(9,13): error CS0246: The type or namespace name 'SnaffleRunner' could not be found (are you missing a using

directive or an assembly reference?)

Snaffler.cs(9,40): error CS0246: The type or namespace name 'SnaffleRunner' could not be found (are you missing a using

directive or an assembly reference?)

Any and all help is appreciated.

**Comment by l0ss** [comment]
I strongly recommend using visual studio rather than trying to do it from the command line but I suspect you need to target snaffler.sln instead of cd’ing into the snaffler dir. On 19 Feb 2023, at 23:36, mrmeeseeks2014 ***@***.***> wrote:﻿
I am trying to download and compile Snaffler into and exe.
I downloaded Snaffler master folder from: https://github.com/SnaffCon/Snaffler
I downloaded .NET developer framework from: https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48
I opened cmd and navigated to the snaffler-master\snaffler folder, then ran c:\Windows[Microsoft.NET](https://microsoft.net/)\Framework\v4.0.30319\csc.exe /t:exe /out:snaffler.exe Snaffler.cs
Received the following results:
Microsoft (R) Visual C# Compiler version 4.8.4084.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.
This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240
Snaffler.cs(9,13): error CS0246: The type or namespace name 'SnaffleRunner' could not be found (are you missing a using
directive or an assembly reference?)
Snaffler.cs(9,40): error CS0246: The type or namespace name 'SnaffleRunner' could not be found (are you missing a using
directive or an assembly reference?)
Any and all help is appreciated.
