### ISSUE TITLE
Any plans to make a Linux/MacOS executable in a release?

### ISSUE THREAD

**Issue by OhZedTee** [SnaffCon/Snaffler#133]
Would love to play around with this tool, but I only have Mac computers. I wonder if there are plans to make a mac executable or a script to run this tool on a Linux/Mac machine.

**Comment by l0ss** [comment]
The AD/SMB aspects of snaffler rely heavily on the way Windows handles those things transparently for the user. I have previously put together a working cross-platform "proof of concept" with the limitation being that it can't do the share discovery stuff, only the tree-walking + file scanning stuff on a filesystem/share that you *already have mounted*. If that would be useful I can release that version, otherwise you'll just have to run regular Snaffler from a Windows VM.
