### ISSUE TITLE
Deduplicate findings

### ISSUE THREAD

**Issue by tigre-bleu** [SnaffCon/Snaffler#86]
It happens sometimes that the exact same result is found several times in the output log (at least the log file, I do not use much the stdout output). 

Example of duplicated output:

```
[xxx@xxx] 2022-02-15 11:37:56Z [File] {Black}<KeepExtExactBlack|R|^\.kdbx$|2,7kB|2022-02-10 16:38:21Z>(\\toto\share\KEEPASS\user.kdbx) .kdbx
[xxx@xxx] 2022-02-15 11:47:18Z [File] {Black}<KeepExtExactBlack|R|^\.kdbx$|2,7kB|2022-02-10 16:38:21Z>(\\toto\share\KEEPASS\user.kdbx) .kdbx
```

Maybe this is related to several workers finding the same thing, I don't know. However this is quite a problem with big networks because it can lead to a log that is twice the normal length and a lot longer to read.

Some deduplication mechanism could be implemented either before writing the log entry or at the end before closing the file.

**Comment by l0ss** [comment]
Yep, sorry, this is a result of accidental duplicate rules in the default rule set. I'm currently working on reworking the entire default ruleset and I believe I've removed all the duplicates.
If you'd like to take the new ruleset for a spin, check out the 'new-rules' branch, otherwise it should hit master within the next week or so.

**Comment by tigre-bleu** [comment]
I can confirm that it's fixed :+1:
